import { StyleSheet } from 'react-native';
import { palette } from './theme/palette';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#e8eee8',
  },
  phone: {
    flex: 1,
    backgroundColor: palette.paper,
  },
  loadingBanner: {
    backgroundColor: palette.mint,
    left: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    position: 'absolute',
    right: 16,
    top: 12,
    zIndex: 4,
  },
  loadingText: {
    color: palette.green,
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
  },
  screenContent: {
    paddingHorizontal: 22,
    paddingTop: 28,
    paddingBottom: 120,
  },
  header: {
    marginBottom: 20,
  },
  screenTitle: {
    color: palette.ink,
    fontSize: 29,
    fontWeight: '800',
  },
  screenSubtitle: {
    color: palette.muted,
    fontSize: 15,
    marginTop: 6,
  },
  heroCard: {
    backgroundColor: palette.cream,
    borderRadius: 8,
    padding: 20,
    borderWidth: 1,
    borderColor: '#eadfcf',
  },
  cardKicker: {
    color: palette.green,
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: palette.ink,
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 31,
    marginTop: 10,
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 18,
  },
  eventChip: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderColor: '#e1d5c5',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  chipIcon: {
    alignItems: 'center',
    backgroundColor: palette.greenSoft,
    borderRadius: 14,
    height: 27,
    justifyContent: 'center',
    width: 27,
  },
  eventChipText: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: '700',
    maxWidth: 170,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 18,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: palette.green,
    borderRadius: 8,
    flex: 1,
    paddingVertical: 15,
  },
  primaryButtonText: {
    color: palette.white,
    fontSize: 15,
    fontWeight: '800',
  },
  secondaryButton: {
    alignItems: 'center',
    borderColor: palette.line,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    paddingVertical: 15,
  },
  secondaryButtonText: {
    color: palette.green,
    fontSize: 15,
    fontWeight: '800',
  },
  privacyStrip: {
    alignItems: 'center',
    backgroundColor: palette.mint,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
    padding: 15,
  },
  privacyText: {
    color: palette.ink,
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  tabBar: {
    alignItems: 'center',
    backgroundColor: palette.white,
    borderTopColor: palette.line,
    borderTopWidth: 1,
    bottom: 0,
    flexDirection: 'row',
    height: 84,
    left: 0,
    paddingHorizontal: 10,
    position: 'absolute',
    right: 0,
  },
  tabItem: {
    alignItems: 'center',
    flex: 1,
    gap: 4,
    justifyContent: 'center',
  },
  tabItemBeforeFab: {
    marginRight: 34,
  },
  tabItemAfterFab: {
    marginLeft: 34,
  },
  activeDot: {
    backgroundColor: palette.green,
    borderRadius: 3,
    height: 6,
    marginBottom: 2,
    width: 6,
  },
  tabLabel: {
    color: '#9fa7a1',
    fontSize: 12,
    fontWeight: '700',
  },
  tabLabelActive: {
    color: palette.green,
  },
  fab: {
    alignItems: 'center',
    backgroundColor: palette.green,
    borderColor: palette.paper,
    borderRadius: 34,
    borderWidth: 5,
    bottom: 48,
    height: 68,
    justifyContent: 'center',
    left: '50%',
    marginLeft: -34,
    position: 'absolute',
    width: 68,
  },
  dayHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  dateNav: {
    flexDirection: 'row',
    gap: 8,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: palette.white,
    borderColor: palette.line,
    borderRadius: 8,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  iconButtonSpacer: {
    height: 44,
    width: 44,
  },
  timeline: {
    gap: 0,
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: palette.white,
    borderColor: palette.line,
    borderRadius: 8,
    borderWidth: 1,
    padding: 24,
  },
  emptyTitle: {
    color: palette.ink,
    fontSize: 17,
    fontWeight: '800',
    marginTop: 10,
  },
  emptyText: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
    textAlign: 'center',
  },
  timelineRow: {
    flexDirection: 'row',
    gap: 14,
  },
  timelineRail: {
    alignItems: 'center',
    width: 54,
  },
  timeText: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 8,
  },
  railDot: {
    backgroundColor: palette.green,
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  railLine: {
    backgroundColor: palette.line,
    flex: 1,
    minHeight: 128,
    width: 2,
  },
  entryCard: {
    backgroundColor: palette.white,
    borderColor: palette.line,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    marginBottom: 18,
    padding: 15,
  },
  suggestedCard: {
    borderColor: palette.green,
    borderStyle: 'dashed',
    opacity: 0.88,
  },
  entryTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  entryTime: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: '800',
  },
  moodChip: {
    backgroundColor: palette.greenSoft,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  moodText: {
    color: palette.green,
    fontSize: 12,
    fontWeight: '800',
  },
  suggestedLabel: {
    color: palette.coral,
    fontSize: 12,
    fontWeight: '800',
    marginLeft: 'auto',
  },
  entryText: {
    color: palette.ink,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 12,
  },
  imagePlaceholder: {
    alignItems: 'center',
    backgroundColor: palette.blue,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    height: 86,
    justifyContent: 'center',
    marginTop: 12,
    overflow: 'hidden',
  },
  imagePlaceholderLarge: {
    height: 190,
  },
  imagePlaceholderText: {
    color: palette.white,
    fontSize: 14,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  miniActionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  miniPrimary: {
    backgroundColor: palette.green,
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 9,
  },
  miniPrimaryText: {
    color: palette.white,
    fontSize: 13,
    fontWeight: '800',
  },
  miniSecondary: {
    backgroundColor: '#eef2ee',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 9,
  },
  miniSecondaryText: {
    color: palette.green,
    fontSize: 13,
    fontWeight: '800',
  },
  yearAgoCard: {
    alignItems: 'center',
    backgroundColor: palette.mint,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
    padding: 18,
  },
  yearAgoText: {
    flex: 1,
  },
  sectionKicker: {
    color: palette.green,
    fontSize: 13,
    fontWeight: '800',
  },
  yearAgoTitle: {
    color: palette.ink,
    fontSize: 22,
    fontWeight: '800',
    lineHeight: 29,
    marginTop: 6,
  },
  stackThumbs: {
    height: 74,
    width: 98,
  },
  stackThumb: {
    borderColor: palette.white,
    borderRadius: 8,
    borderWidth: 3,
    height: 58,
    position: 'absolute',
    width: 58,
  },
  stackThumbOffset: {
    left: 20,
    top: 8,
  },
  stackThumbLast: {
    left: 40,
    top: 16,
  },
  sectionTitle: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 12,
  },
  reelCard: {
    alignItems: 'center',
    backgroundColor: palette.white,
    borderColor: palette.line,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
    padding: 12,
  },
  videoThumb: {
    alignItems: 'center',
    aspectRatio: 16 / 9,
    borderRadius: 8,
    justifyContent: 'center',
    width: 104,
  },
  reelMeta: {
    flex: 1,
  },
  reelTitle: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: '800',
  },
  reelDate: {
    color: palette.muted,
    fontSize: 13,
    marginTop: 4,
  },
  countChip: {
    backgroundColor: palette.cream,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  countChipText: {
    color: palette.green,
    fontSize: 11,
    fontWeight: '800',
  },
  settingsCard: {
    backgroundColor: palette.white,
    borderColor: palette.line,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 16,
    padding: 15,
  },
  settingsRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 12,
  },
  settingsIcon: {
    alignItems: 'center',
    backgroundColor: palette.mint,
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  settingsIconDanger: {
    backgroundColor: '#f8e0dc',
  },
  settingsTextBox: {
    flex: 1,
  },
  settingsTitle: {
    color: palette.ink,
    fontSize: 15,
    fontWeight: '800',
  },
  settingsSubtitle: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 3,
  },
  dangerText: {
    color: palette.coral,
  },
  toggleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
  },
  footerLinks: {
    gap: 10,
    paddingBottom: 16,
  },
  footerLink: {
    color: palette.green,
    fontSize: 14,
    fontWeight: '800',
  },
  modalScrim: {
    backgroundColor: 'rgba(18, 24, 20, 0.32)',
    flex: 1,
  },
  sheet: {
    backgroundColor: palette.paper,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    bottom: 0,
    left: 0,
    minHeight: '55%',
    padding: 22,
    position: 'absolute',
    right: 0,
  },
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: '#ccd3ce',
    borderRadius: 2,
    height: 4,
    marginBottom: 18,
    width: 46,
  },
  sheetTitle: {
    color: palette.ink,
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 16,
  },
  sheetAction: {
    alignItems: 'center',
    backgroundColor: palette.white,
    borderColor: palette.line,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
    padding: 14,
  },
  sheetIcon: {
    alignItems: 'center',
    backgroundColor: palette.mint,
    borderRadius: 8,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  sheetActionText: {
    flex: 1,
  },
  sheetActionTitle: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: '800',
  },
  sheetActionSubtitle: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 3,
  },
  composerRoot: {
    backgroundColor: palette.paper,
    flex: 1,
  },
  composerHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  composerTitle: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: '800',
  },
  composerContent: {
    padding: 22,
    paddingBottom: 110,
  },
  addPhotoBox: {
    alignItems: 'center',
    backgroundColor: palette.white,
    borderColor: palette.line,
    borderRadius: 8,
    borderStyle: 'dashed',
    borderWidth: 1,
    gap: 8,
    height: 170,
    justifyContent: 'center',
  },
  addPhotoText: {
    color: palette.green,
    fontSize: 15,
    fontWeight: '800',
  },
  metaBox: {
    alignItems: 'center',
    backgroundColor: palette.mint,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
    padding: 13,
  },
  metaText: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: '700',
  },
  fieldLabel: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 10,
    marginTop: 22,
  },
  moodRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 9,
  },
  moodOption: {
    backgroundColor: palette.white,
    borderColor: palette.line,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: 'center',
    gap: 4,
  },
  moodOptionSelected: {
    backgroundColor: palette.greenSoft,
    borderColor: palette.green,
  },
  moodEmoji: {
    fontSize: 20,
  },
  moodOptionText: {
    color: palette.ink,
    fontSize: 12,
    fontWeight: '800',
  },
  moodOptionTextSelected: {
    color: palette.green,
  },
  noteInput: {
    backgroundColor: palette.white,
    borderColor: palette.line,
    borderRadius: 8,
    borderWidth: 1,
    color: palette.ink,
    fontSize: 15,
    minHeight: 118,
    padding: 14,
    textAlignVertical: 'top',
  },
  aiCard: {
    backgroundColor: palette.cream,
    borderColor: '#e4d7c4',
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 14,
    padding: 14,
  },
  aiHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
    marginBottom: 9,
  },
  aiTitle: {
    color: palette.green,
    fontSize: 13,
    fontWeight: '800',
  },
  aiText: {
    color: palette.ink,
    fontSize: 15,
    lineHeight: 22,
  },
  composerFooter: {
    backgroundColor: palette.paper,
    borderTopColor: palette.line,
    borderTopWidth: 1,
    bottom: 0,
    left: 0,
    padding: 18,
    position: 'absolute',
    right: 0,
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: palette.green,
    borderRadius: 8,
    paddingVertical: 16,
  },
  saveButtonText: {
    color: palette.white,
    fontSize: 16,
    fontWeight: '800',
  },
  dialogScrim: {
    alignItems: 'center',
    backgroundColor: 'rgba(18, 24, 20, 0.38)',
    flex: 1,
    justifyContent: 'center',
    padding: 22,
  },
  dialogCard: {
    backgroundColor: palette.paper,
    borderRadius: 8,
    padding: 18,
    width: '100%',
  },
  dialogTitle: {
    color: palette.ink,
    fontSize: 20,
    fontWeight: '800',
  },
  dialogText: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  confirmInput: {
    backgroundColor: palette.white,
    borderColor: palette.line,
    borderRadius: 8,
    borderWidth: 1,
    color: palette.ink,
    fontSize: 16,
    fontWeight: '800',
    marginTop: 14,
    padding: 12,
  },
  dialogActions: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-end',
    marginTop: 16,
  },
  dialogSecondary: {
    backgroundColor: '#eef2ee',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  dialogSecondaryText: {
    color: palette.green,
    fontSize: 14,
    fontWeight: '800',
  },
  dialogDanger: {
    backgroundColor: palette.coral,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  dialogDangerText: {
    color: palette.white,
    fontSize: 14,
    fontWeight: '800',
  },
  moodCalendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
    marginTop: 16,
  },
  moodDayCell: {
    alignItems: 'center',
    backgroundColor: palette.white,
    borderColor: palette.line,
    borderRadius: 8,
    borderWidth: 1,
    padding: 10,
    width: '30.7%',
  },
  moodDayName: {
    color: palette.green,
    fontSize: 12,
    fontWeight: '800',
  },
  moodDateText: {
    color: palette.muted,
    fontSize: 12,
    marginTop: 2,
  },
  moodDotLarge: {
    backgroundColor: palette.green,
    borderRadius: 13,
    height: 26,
    marginTop: 10,
    width: 26,
  },
  moodCellText: {
    color: palette.ink,
    fontSize: 12,
    fontWeight: '800',
    marginTop: 8,
  },
  moodCountText: {
    color: palette.muted,
    fontSize: 11,
    marginTop: 2,
  },
});
